### ISSUE TITLE
How to make sockjs work with expressjs 4

### ISSUE THREAD

**Issue by rajkaran** [sockjs/sockjs-node#204]
I have generated my expressjs 4 app with Yeoman-generator and now trying to add sockjs into it. The example code I have found so far is for the older versions of expressjs. Not sure what I am missing, below is my code

**Server side** 
webSocketSimulator.js

```
var express = require('express');
var router = express.Router();
var sockjs = require('sockjs');

module.exports = function (app, server) {
    app.use('/', router);

    var connections = [];

    var sockjs_echo = sockjs.createServer();
    sockjs_echo.on('connection', function(conn) {
        connections.push(conn);
        var number = connections.length;
        conn.write("Welcome, User " + number);
        conn.on('data', function(message) {
            for (var ii=0; ii < connections.length; ii++) {
                connections[ii].write("User " + number + " says: " + message);
            }
        });
        conn.on('close', function() {
            for (var ii=0; ii < connections.length; ii++) {
                connections[ii].write("User " + number + " has disconnected");
            }
        });
    });

    sockjs_echo.installHandlers(server, {prefix:'/chat'});
};
```

**Client side** 
websocketSimulator.jade

```
doctype html
html(lang='en')
  head
    meta(charset='UTF-8')
    meta(name='viewport', content='width=device-width')
    title= title
    block css
      link(rel='stylesheet', href='/css/style.css')
    block js
      if ENV_DEVELOPMENT
        script(src='http://whflipdev01.wh.tvh.ca:35729/livereload.js')
      script(src='http://whflipdev01.wh.tvh.ca:3000/components/jquery/dist/jquery.js')
      script(src='http://whflipdev01.wh.tvh.ca:3000/components/sockjs-client/dist/sockjs.js')
      script(src='http://whflipdev01.wh.tvh.ca:3000/js/websocketSimulate.js')

  body
    block content
      h1= title
      p Welcome to #{title}
      input#search(type="search", placeholder="Search ")
      h2#results
```

websocketSimulate.js

```
var sock = new SockJS('http://' + document.location.hostname + ':3000/chat');

$('#search').on('click', function(e){
        var parameters = { search: $(this).val() };
        sock.send(parameters);
    });

sock.onmessage = function(msg) {
    //var message = JSON.parse(msg.data);

    $('#results').html( msg);
}
```

**UPDATE** - Adding configuration files code.
I have got preset configuration from Yeoman Generator and I am just copy and pasting that code below.

app.js

```
var express = require('express');
var config = require('./config/config');

var app = express();
var expressWs = require('express-ws')(app);
var server = require('http').createServer(app);

require('./config/express')(app, config, server);

app.listen(config.port, function () {
  console.log('Express server listening on port ' + config.port);
});
```

express.js

```
var express = require('express');
var glob = require('glob');

var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var compress = require('compression');
var methodOverride = require('method-override');
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type');
    next();
}

module.exports = function(app, config, server) {
  var env = process.env.NODE_ENV || 'development';
  app.locals.ENV = env;
  app.locals.ENV_DEVELOPMENT = env == 'development';

  app.set('views', config.root + '/app/views');
  app.set('view engine', 'jade');

  // app.use(favicon(config.root + '/public/img/favicon.ico'));
  app.use(logger('dev'));
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({
    extended: true
  }));
  app.use(cookieParser());
  app.use(compress());
  app.use(express.static(config.root + '/public'));
  app.use(methodOverride());
  app.use(allowCrossDomain);

  var controllers = glob.sync(config.root + '/app/controllers/*.js');
  controllers.forEach(function (controller) {
    require(controller)(app, server);
  });

  app.use(function (req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
  });

  if(app.get('env') === 'development'){
    app.use(function (err, req, res, next) {
      res.status(err.status || 500);
      res.render('error', {
        message: err.message,
        error: err,
        title: 'error'
      });
    });
  }

  app.use(function (err, req, res, next) {
    res.status(err.status || 500);
      res.render('error', {
        message: err.message,
        error: {},
        title: 'error'
      });
  });

};
```

config.js

```
var path = require('path'),
    rootPath = path.normalize(__dirname + '/..'),
    env = process.env.NODE_ENV || 'development';

var config = {
  development: {
    root: rootPath,
    app: {
      name: 'nodejswebsocketapp'
    },
    port: process.env.PORT || 3000,
  },

  test: {
    root: rootPath,
    app: {
      name: 'nodejswebsocketapp'
    },
    port: process.env.PORT || 3000,
  },

  production: {
    root: rootPath,
    app: {
      name: 'nodejswebsocketapp'
    },
    port: process.env.PORT || 3000,
  }
};

module.exports = config[env];
```

**Comment by brycekahle** [comment]
What behavior/errors are you seeing?

**Comment by rajkaran** [comment]
This is the error I gets

```
[grunt-develop] > C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\sockjs\lib\utils.js:82
    old_listeners = ee.listeners(event).slice(0);
                      ^
TypeError: Cannot read property 'listeners' of undefined
    at Object.exports.overshadowListeners (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\sockjs\lib\utils.js:82:23)
    at Server.installHandlers (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\sockjs\lib\sockjs.js:204:13)
    at module.exports (C:\xampp\htdocs\xtras\nodejsWebSocketApp\app\controllers\webSocketSimulator.js:31:14)
    at C:\xampp\htdocs\xtras\nodejsWebSocketApp\config\express.js:39:24
    at Array.forEach (native)
    at module.exports (C:\xampp\htdocs\xtras\nodejsWebSocketApp\config\express.js:38:15)
    at Object.<anonymous> (C:\xampp\htdocs\xtras\nodejsWebSocketApp\app.js:10:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
>> application exited with code 1
```

**Comment by brycekahle** [comment]
So it looks like the `server` parameter used in `webSocketSimulator.js` is `undefined`. Where are you `require`-ing that file and calling it?

**Comment by rajkaran** [comment]
I have created `server` parameter in `app.js` file and passing it to every controller in `express.js` file. 

I made a small change to express.js file so, error is gone now.
_from_
```
var controllers = glob.sync(config.root + '/app/controllers/*.js');
  controllers.forEach(function (controller, server) {
    require(controller)(app);
  });
```
_to_
```
var controllers = glob.sync(config.root + '/app/controllers/*.js');
  controllers.forEach(function (controller) {
    require(controller)(app, server);
  });
```

Now I am getting this : 

` GET /chat/info?t=1464717105054 404 35.747 ms`

Can't make websocket connection.

I can confirm that server parameter is not undefined anymore I can console.log it. Result of console.log(server)

```
[grunt-develop] > { domain: null,
  _events:
   { request:
      { [Function]
        domain: undefined,
        _events: [Object],
        _maxListeners: undefined,
        setMaxListeners: [Function: setMaxListeners],
        emit: [Function: emit],
        addListener: [Function: addListener],
        on: [Function: addListener],
        once: [Function: once],
        removeListener: [Function: removeListener],
        removeAllListeners: [Function: removeAllListeners],
        listeners: [Function: listeners],
        init: [Function: init],
        defaultConfiguration: [Function: defaultConfiguration],
        lazyrouter: [Function: lazyrouter],
        handle: [Function: handle],
        use: [Function: use],
        route: [Function: route],
        engine: [Function: engine],
        param: [Function: param],
        set: [Function: set],
        path: [Function: path],
        enabled: [Function: enabled],
        disabled: [Function: disabled],
        enable: [Function: enable],
        disable: [Function: disable],
        checkout: [Function],
        connect: [Function],
        copy: [Function],
        delete: [Function],
        get: [Function],
        head: [Function],
        lock: [Function],
        'm-search': [Function],
        merge: [Function],
        mkactivity: [Function],
        mkcol: [Function],
        move: [Function],
        notify: [Function],
        options: [Function],
        patch: [Function],
        post: [Function],
        propfind: [Function],
        proppatch: [Function],
        purge: [Function],
        put: [Function],
        report: [Function],
        search: [Function],
        subscribe: [Function],
        trace: [Function],
        unlock: [Function],
        unsubscribe: [Function],
        all: [Function: all],
        del: [Function],
        render: [Function: render],
        listen: [Function: serverListen],
        request: [Object],
        response: [Object],
        cache: {},
        engines: {},
        settings: [Object],
        locals: [Object],
        mountpath: '/',
        ws: [Function: addWsRoute],
        _router: [Object] },
     connection: [Function: connectionListener],
     clientError: [Function] },
  _maxListeners: undefined,
  _connections: 0,
  _handle: null,
  _usingSlaves: false,
  _slaves: [],
  allowHalfOpen: true,
  pauseOnConnect: false,
  httpAllowHalfOpen: false,
  timeout: 120000 }
```

**Comment by emgould** [comment]
Did you ever resolve this and if so how?

**Comment by TimoRuetten** [comment]
If anyone else is facing the problem - this is what worked for me:

```
const server = http.createServer(app);
sockjsEcho.installHandlers(server, { prefix: '/echo' });
```

Change to:

```
const server = app.listen(PORT);
sockjsEcho.installHandlers(server, { prefix: '/echo' });
```
