### ISSUE TITLE
sockjs on npm is missing lib/

### ISSUE THREAD

**Issue by ghost** [sockjs/sockjs-node#86]
To reproduce:

```
$ npm install sockjs
$ node
> require('sockjs')
Error: Cannot find module './lib/sockjs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/substack/projects/scratch/s/node_modules/sockjs/index.js:1:80)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
> ^D
$ ls node_modules/sockjs/
Changelog  COPYING  examples  index.js  LICENSE-MIT-SockJS  Makefile  node_modules  package.json  README.md
```

**Comment by martinkarlsson** [comment]
I also get the exact same error: 
Error: Cannot find module './lib/sockjs
On Github, there is no lib/sockjs.js in sockjs-node - how can I solve this?
